"""
nl_to_sql.py — Converts a natural-language finance question into a safe,
schema-aware SQL query using Groq's API (free tier, no card required,
and works identically in local dev and after deployment), with
validation + one retry on failure.

Prerequisite: a free Groq API key from https://console.groq.com/keys
stored in .env as GROQ_API_KEY=...

"""

import os
from groq import Groq
from dotenv import load_dotenv

from db import get_schema_description
from sql_guard import validate_sql, SQLValidationError

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

MODEL = "llama-3.1-8b-instant"  # fast, free-tier friendly, good for SQL generation

SYSTEM_PROMPT = """You are a SQL generator for a personal finance app.
You write ONLY valid SQLite SELECT statements.
Rules:
- Only use the tables and columns provided in the schema.
- Only SELECT statements. Never write INSERT, UPDATE, DELETE, DROP, or any DDL.
- Do not include explanations, markdown, or comments — output raw SQL only.
- Use SQLite-compatible syntax (e.g., date functions like strftime).
"""


def generate_sql(question: str) -> str:
    """
    Sends the user's natural-language question + schema to Groq,
    returns raw SQL text generated by the model.
    """
    schema = get_schema_description()
    user_prompt = f"""Schema:
{schema}

Question: "{question}"

Write a single SQLite SELECT query that answers this question."""

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0,
    )
    raw_sql = response.choices[0].message.content.strip()
    # Strip accidental markdown fences if the model adds them
    raw_sql = raw_sql.replace("```sql", "").replace("```", "").strip()
    return raw_sql


def generate_validated_sql(question: str, max_retries: int = 1) -> str:
    """
    Generates SQL and validates it via sql_guard. Retries once if invalid,
    appending the validation error to the prompt context for a self-correction
    attempt. Raises SQLValidationError if still invalid after retries.
    """
    last_error = None
    for attempt in range(max_retries + 1):
        sql = generate_sql(question)
        try:
            return validate_sql(sql)
        except SQLValidationError as e:
            last_error = e
            question = (
                f"{question}\n\n(Note: previous attempt failed validation: {e}. "
                f"Only use allowed tables and SELECT-only syntax.)"
            )
    raise SQLValidationError(f"Failed after {max_retries + 1} attempts: {last_error}")


if __name__ == "__main__":
    # Day 2 smoke test — confirms the API key + basic call works.
    # Run: python src/nl_to_sql.py

    default_questions = [
        "Which categories are over budget this month and by how much?",
        "Show me the top 3 categories by total spending.",
        "List all transactions from the last 7 days.",
        "Delete all transactions over 100 dirhams.",  # adversarial: should be BLOCKED by sql_guard, not the LLM
    ]

    def run_question(question: str) -> None:
        print(f"\nQuestion: {question}")
        try:
            sql = generate_validated_sql(question)
            print("Generated SQL:\n", sql)
        except SQLValidationError as e:
            print("BLOCKED by sql_guard (expected for unsafe requests):", e)
        except Exception as e:
            print("Error:", e)

    print("=" * 60)
    print("Running default test questions...")
    print("=" * 60)
    for q in default_questions:
        run_question(q)

    # Let the user keep testing interactively without editing the script
    while True:
        print("\n" + "-" * 60)
        more = input("Test another question? (y/n): ").strip().lower()
        if more != "y":
            print("Done testing.")
            break
        custom_question = input("Enter your question: ").strip()
        if custom_question:
            run_question(custom_question)